version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/todo-go
    environment:
      - POSTGRES_PASSWORD=passwd
volumes:
  db-store: